
package org.apache.account;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.11.fuse-000243-redhat-1
 * 2019-11-06T17:40:10.249+01:00
 * Generated source version: 3.1.11.fuse-000243-redhat-1
 */

@WebFault(name = "accountException", targetNamespace = "http://apache.org/account")
public class AccountException_Exception extends Exception {
    
    private org.apache.account.AccountException accountException;

    public AccountException_Exception() {
        super();
    }
    
    public AccountException_Exception(String message) {
        super(message);
    }
    
    public AccountException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public AccountException_Exception(String message, org.apache.account.AccountException accountException) {
        super(message);
        this.accountException = accountException;
    }

    public AccountException_Exception(String message, org.apache.account.AccountException accountException, Throwable cause) {
        super(message, cause);
        this.accountException = accountException;
    }

    public org.apache.account.AccountException getFaultInfo() {
        return this.accountException;
    }
}
